name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  continuous-deployment:

    runs-on: ubuntu-latest
    
    env:
      IS_GITHUB_ACTION: true

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Start MSSQL
      run: docker-compose -f src/tests/Configuration.EFCore.IntegrationTest/dockercompose-integrationtest.yml up -d
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore src/Configuration.EFCore.sln
    - name: Build
      run: dotnet build src/Configuration.EFCore.sln --configuration Release --no-restore
    - name: Unit Test
      run: dotnet test src/tests/Configuration.EFCore.UnitTest --no-restore --verbosity normal
    - name: Integration Test
      run: dotnet test src/tests/Configuration.EFCore.IntegrationTest --no-restore --verbosity normal
    - name: Publish EFCore.Audit nuget package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/Configuration.EFCore/Configuration.EFCore.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
